# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 106962a
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
active: false
github_repo_name: nodal
project_description: Nodal network analyzer for Matlab.
project_email: blake.naccarato@gmail.com
project_name: nodalpy
project_owner_github_username: blakeNaccarato
project_owner_name: blakeNaccarato
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2023
